version: "3"
services:
  backend:
    build: nest-api
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./nest-api:/usr/src/app

  frontend:
    build: react-app
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3001:3000"
    volumes:
      - ./react-app:/usr/src/app
    depends_on:
      - backend